export const STATE = {
	IDLE_TOP: 'IDLE_TOP',
	IDLE_BOTTOM: 'IDLE_BOTTOM',
	IDLE_LEFT: 'IDLE_LEFT',
	IDLE_RIGHT: 'IDLE_RIGHT',
	WALK_TOP: 'WALK_TOP',
	WALK_BOTTOM: 'WALK_BOTTOM',
	WALK_LEFT: 'WALK_LEFT',
	WALK_RIGHT: 'WALK_RIGHT',
}
